### Data Wrangling Practice in Python

In [1]:
import numpy as np 
import pandas as pd 
from pathlib import Path
# import matplotlib.pyplot as plt

In [2]:
# Import data from .csv

project_dir = Path.cwd().parent
print(f"Project directory: {project_dir}")

data_dir = project_dir / "src" / "data" / "raw"

# with open(data_dir / "dataset_2.csv", "r") as f:
#     df = pd.read_csv(f, header = 0)
#     print(df.head())

with open(data_dir / 'dataset_2.csv', 'r') as f:
    df = pd.read_csv(f)
    display(df.head())

Project directory: C:\Users\steph\Documents\GitHub\Smokey_pipeline_mazes

,Area_SqFt,Rooms,Build_Year,Location,Street_Type,Furnishing,Property_Type,Has_Pool,Price
0,2473.192784,4.0,1992,Jaipur,Residential Lane,Furnished,Apartment,No,568486.0
1,2353.472711,4.0,2006,Indore,Corner Plot,Unfurnished,Apartment,Yes,577214.0
2,2212.222005,3.0,2012,Jaipur,Highway Facing,Semi-Furnished,Duplex,No,581300.0
3,2823.886596,6.0,1993,Lucknow,Main Road,Unfurnished,Villa,Yes,794614.0
4,1869.648721,5.0,2012,Jaipur,Corner Plot,Semi-Furnished,Apartment,No,493086.0

In [3]:
df.describe(include = 'all')

,Area_SqFt,Rooms,Build_Year,Location,Street_Type,Furnishing,Property_Type,Has_Pool,Price
count,1091.000000,1091.000000,1124.000000,1124,1124,1091,1124,1124,1.124000e+03
unique,NaN,NaN,NaN,8,5,3,4,2,NaN
top,NaN,NaN,NaN,Noida,Highway Facing,Semi-Furnished,Apartment,No,NaN
freq,NaN,NaN,NaN,156,242,451,536,827,NaN
mean,2237.479473,4.568286,2005.080071,NaN,NaN,NaN,NaN,NaN,6.082015e+05
std,731.097828,1.678155,11.708876,NaN,NaN,NaN,NaN,NaN,1.431958e+05
min,700.000000,2.000000,1985.000000,NaN,NaN,NaN,NaN,NaN,2.486400e+05
25%,1834.022964,3.000000,1995.000000,NaN,NaN,NaN,NaN,NaN,5.161948e+05
50%,2201.545784,5.000000,2005.000000,NaN,NaN,NaN,NaN,NaN,6.025410e+05
75%,2576.139355,6.000000,2015.000000,NaN,NaN,NaN,NaN,NaN,6.895785e+05
max,10267.124330,7.000000,2024.000000,NaN,NaN,NaN,NaN,NaN,2.071402e+06

In [4]:
assign = ['one', 'two', 'three']

In [9]:
df[new_col] = df['Furnishing'].apply(lambda x: assign[x])

TypeError: list indices must be integers or slices, not str

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1124 entries, 0 to 1123
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Area_SqFt      1091 non-null   float64
 1   Rooms          1091 non-null   float64
 2   Build_Year     1124 non-null   int64
 3   Location       1124 non-null   object
 4   Street_Type    1124 non-null   object
 5   Furnishing     1091 non-null   object
 6   Property_Type  1124 non-null   object
 7   Has_Pool       1124 non-null   object
 8   Price          1124 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 79.2+ KB

In [18]:
# check fo r duplicates:

#df[df.duplicated()]   # No duplicates found

print(df[df.duplicated()])

df[df.duplicated()]

Empty DataFrame
Columns: [Area_SqFt, Rooms, Build_Year, Location, Street_Type, Furnishing, Property_Type, Has_Pool, Price]
Index: []

Empty DataFrame
Columns: [Area_SqFt, Rooms, Build_Year, Location, Street_Type, Furnishing, Property_Type, Has_Pool, Price]
Index: []

In [26]:
#df[df.isna()]

nulls = df[df.isna()]

nulls.head()

,Area_SqFt,Rooms,Build_Year,Location,Street_Type,Furnishing,Property_Type,Has_Pool,Price
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
nulls = df.isna().sum()
nulls

Area_SqFt        33
Rooms            33
Build_Year        0
Location          0
Street_Type       0
Furnishing       33
Property_Type     0
Has_Pool          0
Price             0
dtype: int64

In [29]:
def dropnas(df): 
    nas = df.isna()
    num = df.isna().sum()
    percent = (df.isna().mean() * 100)
    missing_df = pd.DataFrame({'Missing Count' : num, 'Missing Percentage': percent})
    
    return missing_df

In [30]:
dropnas(df)

               Missing Count  Missing Percentage
Area_SqFt                 33            2.935943
Rooms                     33            2.935943
Build_Year                 0            0.000000
Location                   0            0.000000
Street_Type                0            0.000000
Furnishing                33            2.935943
Property_Type              0            0.000000
Has_Pool                   0            0.000000
Price                      0            0.000000

In [31]:
def findnas(df):
    null = df.isna()
    count = df.isna().sum()
    percentage = (df.isna().mean() * 100)
    frame = pd.DataFrame({"Missing Count": count, "Missing Percentage": percentage})
    
    return frame

In [33]:
test_df = findnas(df)

In [34]:
test_df

               Missing Count  Missing Percentage
Area_SqFt                 33            2.935943
Rooms                     33            2.935943
Build_Year                 0            0.000000
Location                   0            0.000000
Street_Type                0            0.000000
Furnishing                33            2.935943
Property_Type              0            0.000000
Has_Pool                   0            0.000000
Price                      0            0.000000

In [36]:
# add row for new variable 'sold' with6 NAs and 0.4% missing:

new_row = pd.DataFrame({
    "Missing Count" : ['6', '2'],
    "Missing Percentage": ['0.4', '0.2']
})

new_df = pd.concat([test_df, new_row], ignore_index = True)

In [37]:
new_df

   Missing Count Missing Percentage
0             33            2.93594
1             33            2.93594
2              0                  0
3              0                  0
4              0                  0
5             33            2.93594
6              0                  0
7              0                  0
8              0                  0
9              6                0.4
10             2                0.2

In [38]:
df_1 = new_df.drop('Missing Percentage', axis = 1)
df_1

   Missing Count
0             33
1             33
2              0
3              0
4              0
5             33
6              0
7              0
8              0
9              6
10             2

In [41]:
# adding a row to df:

new_row = pd.DataFrame({
    "Missing Count": [55, 56, 2],
    "Missing Percentage": [2, 3, .2]
})

new_df = pd.concat([test_df, new_row], ignore_index = True)

new_df

    Missing Count  Missing Percentage
0              33            2.935943
1              33            2.935943
2               0            0.000000
3               0            0.000000
4               0            0.000000
5              33            2.935943
6               0            0.000000
7               0            0.000000
8               0            0.000000
9              55            2.000000
10             56            3.000000
11              2            0.200000